<?php

return [
    'sidebar' => [
        [
            'name' => 'Dashboard',
            'order' => 1,
            'target' => '',
            'icon' => 'fas fa-fw fa-tachometer-alt',
            'route' => null,
            'url' => null,
            'vue_route' => "#/",
            'sub_items' => [],
            'permissions' => [],
        ],
        [
            'name' => 'Home page',
            'order' => 2, 
            'target' => '_blank',
            'icon' => 'far fa-fw fa-eye',
            'route' => 'frontend',
            'url' => null,
            'sub_items' => [],
            'permissions' => [],
        ],
        [
            'name' => 'Tickets',
            'order' => 3, 
            'target' => '',
            'icon' => 'fas fa-fw fa-ticket-alt',
            'route' => 'dashboard.tickets',
            'url' => null,
            'sub_items' => [],
            'permissions' => [],
        ],
        [
            'name' => 'Articles',
            'order' => 4, 
            'target' => '',
            'icon' => 'far fa-fw fa-newspaper',
            'route' => null,
            'url' => null,
            'vue_route' => "#/articles",
            'sub_items' => [],
            'permissions' => ['manage_articles'],
        ],
        [
            'name' => 'Categories',
            'order' => 5, 
            'target' => '',
            'icon' => 'fas fa-fw fa-folder-open',
            'route' => null,
            'url' => null,
            'vue_route' => "#/categories",
            'sub_items' => [],
            'permissions' => ['manage_categories'],
        ],
        [
            'name' => 'Saved replies',
            'order' => 6, 
            'target' => '',
            'icon' => 'fas fa-fw fa-reply-all',
            'route' => null,
            'url' => null,
            'vue_route' => "#/saved_replies",
            'sub_items' => [],
            'permissions' => ['create_saved_reply'],
        ],
        [
            'name' => 'Customers',
            'order' => 7, 
            'target' => '',
            'icon' => 'fas fa-fw fa-user',
            'route' => 'dashboard.customers',
            'url' => null,
            'sub_items' => [],
            'permissions' => ['manage_customers'],
        ],
        [
            'name' => 'Employees',
            'order' => 8, 
            'target' => '',
            'icon' => 'fas fa-fw fa-user-tie',
            'route' => 'dashboard.employees',
            'url' => null,
            'sub_items' => [],
            'permissions' => ['manage_employees'],
        ],
        [
            'name' => 'Modules',
            'target' => '',
            'icon' => 'fas fa-boxes',
            'route' => 'dashboard.modules_manager',
            'url' => null,
            'sub_items' => [],
            'permissions' => ['list_modules'],
            'order' => 9
        ],
        "settings" => [
            'name' => 'Settings',
            'label' => 'Settings',
            'order' => 10, 
            'target' => '',
            'icon' => 'fas fa-fw fa-sliders-h',
            'route' => 'dashboard.settings',
            'url' => null,
            'permissions' => ['view_settings'],
            'sub_items' => [],
        ],
    ]
];